### ISSUE TITLE
Nested folders not sending entire path to server [Removed]

### ISSUE THREAD

**Issue by BenMaxfield** [iutbay/mm#3]
[Removed and solved]

Realized it was to do with the path property of the returned server side directory listings, have now fixed and is working as intended. Will keep below for other users if needed:

-----START ORIGINAL-----
If you have a sub folder and click it, the path sent to the server is not complete.

For example, if your top level (initial base path) has a folder called A in it and then you click that folder the server receives the path 'A', however, if that directory (A) contains another folder, called B, then when you click on this folder the path sent to the server is 'B' when it should actually be 'A/B'.

This must be causing an issue for others, or is there an option I am missing? I cannot store the last folder accessed on the server as it needs to be stateless.

Please advise! 

Edit: Am happy to fix myself just not sure where the best place to start with it is, if you could point me in the right direction that would be just as good as committing a fix :)

Thanks for the hard work, everything else seems pretty awesome so far

**Comment by klevron** [comment]
Thanks for your feedback  BenMaxfield
